#!/bin/bash

[ "$0" = 'bash' ] || exec /usr/bin/env bash --rcfile "$0"

_cmd_cfg=(
    'help longalias'
    'project alias'
    'report alias'
    'info alias'
    'modify alias'
    'stop alias'
    'start alias'
    'add alias'
    'today alias'
    'ls alias'
    'active alias'
    'projects alias'
)

for cfg in "${_cmd_cfg[@]}" ; do
    read cmd opts <<< $cfg
    for opt in $opts ; do
        case $opt in
            alias)   alias $cmd="pytask $cmd" ;;
            longalias)   alias $cmd="pytask $cmd | less -F" ;;
        esac
    done
done
PS1='pytask> '

